import { AuthContextProvider } from "@/context/AuthContext";
import { Toaster } from "react-hot-toast";

import "@/styles/defaults/page-setup.css";
import "@/styles/defaults/variables.css";
import "@/styles/defaults/transitions.css";
import Navbar from "./navbar";

export const metadata = {
  title: {
    template: "%s | Acron",
    default: "Acron", // a default is required when creating a template
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <AuthContextProvider>
          <Toaster
            position="top-left"
            reverseOrder={true}
            containerStyle={{
              top: "min(40px, max(4vw, 10px))",
              left: "min(40px, max(4vw, 10px))",
            }}
          />
          <Navbar />
          <main>{children}</main>
        </AuthContextProvider>
      </body>
    </html>
  );
}
