import { AuthContextProvider } from "@/context/AuthContext"
import { Toaster } from "react-hot-toast"

import "@/styles/defaults/page-setup.css"
import "@/styles/defaults/variables.css"
import "@/styles/defaults/transitions.css"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
      </head>
      <body>
        <AuthContextProvider>
          <Toaster
            position="top-left"
            reverseOrder={true}
            containerStyle={{
              top: "min(40px, max(4vw, 10px))",
              left: "min(40px, max(4vw, 10px))"
            }}
          />
          {children}
        </AuthContextProvider>
      </body>
    </html>
  )
}
