import { Fragment } from "react";

export const metadata = {
  title: {
    template: "%s | Acron Accounts",
    default: "Accounts", // a default is required when creating a template
  },
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return <Fragment>{children}</Fragment>;
}
