import style from "@/styles/account.handler.module.css";

export const metadata = {
  title: {
    template: "%s | Acron Accounts",
    default: "Acron Accounts", // a default is required when creating a template
  },
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <section className={style.accountHandler}>
      <div className={style.container}>
        {children}
        <img
          src="https://images.unsplash.com/photo-1635282922712-97888dc706dc?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
          alt=""
        />
        <div className={style.info}>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
            <path d="M7.5 6.75V0h9v6.75h-9zm9 3.75H24V24H0V10.5h7.5v6.75h9V10.5z" />
          </svg>
          <a href="https://unsplash.com/@goyache">Juan Goyache</a>
        </div>
      </div>
    </section>
  );
}
